### ISSUE TITLE
Showing Chromosome arms on the CNV plot 

### ISSUE THREAD

**Issue by moutazhelal** [findlaycopley/PlotCNV#1]
Thank you for making this tool.

I would like to ask if it is possible to plots where arms of the chromosomes start and stop using plotCopynumber() ?

Any help is appreciated

Best,
Moutaz

**Comment by findlaycopley** [comment]
Hi Moutaz!

I've not implemented anything like that as of yet, but it should be relatively straightforward!

First you'd need a vector of the arm positions you want to add to the plot. I'm using getChromInfoFromUCSC to get the chromosome lengths, but this doesn't give arm positions.

Once you've got those, you just need to add those values to the start point for the chromosome those arms are on (these are found at obj@Chr_Starts). This is because the x axis is just one long numerical axis, so you need to modify the per chromosome position so they start within that chromosome on the plot.

Then you can add vertical lines at those locations using something like this:

```
obj@Plot$plot + geom_vline(xintercept = positions_to_plot , 
            linetype = "dashed", 
            colour = "lightgrey")
```

That should add dashed grey lines at the locations you've provided!

Let me know if you have any further questions, or doesn't work etc ... and I can look into it. I'm a little busy presently so I'm not sure I'll have time to properly implement this as a built-in feature, but I'll look into it!

**Comment by moutazhelal** [comment]
Thank you very much for your response @findlaycopley.  I followed what you have suggested and it worked perfectly. by the way thanks for an easy to understand source code. Looking forward to future work

**Comment by findlaycopley** [comment]
I'm so glad it worked for you! Thank you for your kind words! Good luck!
